using BTTCGuildApp.Helpers;

namespace BTTCGuildApp.Models
{
    public enum Class
    {
        [StringValue("Acolyte")] Acolyte,
        [StringValue("Apostle")] Apostle,
        [StringValue("Argent")] Argent,
        [StringValue("Archwizard")] Archwizard,
        [StringValue("Assassin")] Assassin,
        [StringValue("Battle Mage")] BattleMage,
        [StringValue("Beastmaster")] Beastmaster,
        [StringValue("Bladecaller")] Bladecaller,
        [StringValue("Bladedancer")] Bladedancer,
        [StringValue("Brood Warden")] BroodWarden,
        [StringValue("Bowsinger")] Bowsinger,
        [StringValue("Charlatan")] Charlatan,
        [StringValue("Conjurer")] Conjurer,
        [StringValue("Cultist")] Cultist,
        [StringValue("Dreadnought")] Dreadnought,
        [StringValue("Duelist")] Duelist,
        [StringValue("Enchanter")] Enchanter,
        [StringValue("Falconer")] Falconer,
        [StringValue("Guardian")] Guardian,
        [StringValue("Hawkeye")] Hawkeye,
        [StringValue("High Priest")] HighPriest,
        [StringValue("Highsword")] Highsword,
        [StringValue("Hunter")] Hunter,
        [StringValue("Keeper")] Keeper,
        [StringValue("Knight")] Knight,
        [StringValue("Magician")] Magician,
        [StringValue("Minstrel")] Minstrel,
        [StringValue("Necromancer")] Necromancer,
        [StringValue("Nightshield")] Nightshield,
        [StringValue("Nightspell")] Nightspell,
        [StringValue("Oracle")] Oracle,
        [StringValue("Paladin")] Paladin,
        [StringValue("Predator")] Predator,
        [StringValue("Protector")] Protector,
        [StringValue("Scryer")] Scryer,
        [StringValue("Scion")] Scion,
        [StringValue("Scout")] Scout,
        [StringValue("Sentinel")] Sentinel,
        [StringValue("Shadow Caster")] ShadowCaster,
        [StringValue("Shadow Disciple")] ShadowDisciple,
        [StringValue("Shadow Guardian")] ShadowGuardian,
        [StringValue("Shadow Lord")] ShadowLord,
        [StringValue("Shadowblade")] Shadowblade,
        [StringValue("Shadowmancer")] Shadowmancer,
        [StringValue("Shaman")] Shaman,
        [StringValue("Siren")] Siren,
        [StringValue("Song Warden")] SongWarden,
        [StringValue("Songcaller")] Songcaller,
        [StringValue("Soul Weaver")] SoulWeaver,
        [StringValue("Soulbow")] Soulbow,
        [StringValue("Sorcerer")] Sorcerer,
        [StringValue("Spellhunter")] Spellhunter,
        [StringValue("Spellmancer")] Spellmancer,
        [StringValue("Spellsword")] Spellsword,
        [StringValue("Spellshield")] Spellshield,
        [StringValue("Spellstone")] Spellstone,
        [StringValue("Templar")] Templar,
        [StringValue("Tellsword")] Tellsword,
        [StringValue("Trickster")] Trickster,
        [StringValue("Warlock")] Warlock,
        [StringValue("Warden")] Warden,
        [StringValue("Weapon Master")] WeaponMaster,
        [StringValue("Wild Blade")] WildBlade,
    }
}